---
- name: Provision Custom Facts
  hosts: all
  tasks:
    - name: Create custom facts directory
      file: >
        path=/etc/ansible/facts.d
        recurse=yes
        state=directory
    - name: Install custom facts modules
      template: >
        src={{ item }}
        dest=/etc/ansible/facts.d/
        mode=0755
      with_fileglob:
        - facts.d/*
    - name: Reload ansible_local
      setup: filter=ansible_local
