---
- name: restart machine
  raw: 'sleep 5 && reboot "Ansible rebooting system" &'
  async: 0
  poll: 0
  ignore_errors: true
- name: wait for machine to restart
  local_action: wait_for host='{{ inventory_hostname }}' port=22 delay=10
  sudo: false